### ISSUE TITLE
Spectral Helix item infobox broken

### ISSUE THREAD

**Issue by acbeaumo** [Project-Path-of-Exile-Wiki/PyPoE#10]
https://www.poewiki.net/wiki/Spectral_Helix

![Screenshot 2021-10-16 102256](https://user-images.githubusercontent.com/1069322/137591157-6d2ee7ed-1bc6-4eef-9a0a-40c31f01f5e3.jpg)

Exporter inserted a line break for some reason, which causes the infobox template to break. Line breaks should be inserted with `<br>` instead.

![Screenshot 2021-10-16 101916](https://user-images.githubusercontent.com/1069322/137591054-9855eac5-fec3-4192-9f0f-ef73385f1d68.jpg)

**Comment by markliu06** [comment]
Also for 

https://www.poewiki.net/w/index.php?title=Summon_Phantasm_Support&diff=1099750&oldid=1082891

Before fix it will make the page

https://www.poewiki.net/wiki/Version_3.2.0#Major_New_Content_and_Features

like this
![2021-10-16 (2)](https://user-images.githubusercontent.com/67254854/137591471-54def40b-7be0-4ed7-846d-d5d48250778f.png)

**Comment by markliu06** [comment]
Frostblink gem as well, seem all the gem quality text needs to have line break replaced by `<br>`
