### ISSUE TITLE
Improve make_inter_wiki_links mappings

### ISSUE THREAD

**Issue by supereddie** [Project-Path-of-Exile-Wiki/PyPoE#114]
The the Essence of Horror wiki seems to be generated so I hope this is the correct place to mention this.

On the Essence of Horror wiki page, a lot the keywords in the modifier lines have links to the corresponding Wiki pages (for example, in the Boots modifier line the `Elemental Damage` links to the Elemental_Damage page in the Wiki).

I am unsure if these types of links should be in the item description, but if the should, the following are missing or incorrect:

Missing links:
|Mod line|Keyword|Wiki page|
|--|--|--|
|Weapon|Power|Power_Charge|
|Boots|Stationary|Stationary|
|Shield|Chill|Chill|
|Shield|Nearby|Nearby (redirects to Distance#"Nearby")|
|Amulet|Crush|Crushed|
|Belt|Alchemist's Genius|Alchemist%27s_Genius|
|Belt|Flask|Flask|

Incorrect links:
- Weapon: keyword `Frenzy` links to Frenzy skill gem, but should link to Frenzy_Charge.

**Comment by lvlvllvlvllvlvl** [comment]
[[Body Armour]] instead of Body [[Armour]] https://www.poewiki.net/wiki/Mastery_Effect:Life2

**Comment by lvlvllvlvllvlvl** [comment]
[[Shatter]] https://www.poewiki.net/index.php?title=Tattoo_of_the_Arohongui_Warmonger&diff=prev&oldid=1389402
[[Critical Strikes]] https://www.poewiki.net/index.php?title=Tattoo_of_the_Rongokurai_Turtle&diff=prev&oldid=1389404
