### ISSUE TITLE
Outdated boss information not updating

### ISSUE THREAD

**Issue by blvcksvn** [Project-Path-of-Exile-Wiki/PyPoE#143]
The Solaris Temple Level 2 (Act 3)'s area subpage https://www.poewiki.net/wiki/Area:1~3~8~2

incorrectly retains old boss information and is not cleared on export:

|boss_monster_ids                 = Metadata/Monsters/Guardians/GuardianBossHeadFire, Metadata/Monsters/Guardians/GuardianBossHeadCold, Metadata/Monsters/Guardians/GuardianBossHeadLightning

is this a bug or is the field obsolete and therefore no longer checked on export?

**Comment by lvlvllvlvllvlvl** [comment]
Those are still listed as the area bosses in the datafile
![image](https://github.com/Project-Path-of-Exile-Wiki/PyPoE/assets/119665497/a217076e-7141-4f49-b789-2b0d743d8927)
![image](https://github.com/Project-Path-of-Exile-Wiki/PyPoE/assets/119665497/8e0e5bcc-8ba7-47c5-80e3-c7b5a638bba3)

**Comment by blvcksvn** [comment]
Game file issue, not pypoe
