### ISSUE TITLE
Plateau Map (specific series) export - replace guild character "|" with "{{!}}"

### ISSUE THREAD

**Issue by blvcksvn** [Project-Path-of-Exile-Wiki/PyPoE#164]
https://github.com/Project-Path-of-Exile-Wiki/wiki/issues/187

Required to escape pipe character when map character is queried. Please automate if possible to prevent overwrite.

**Comment by lvlvllvlvllvlvl** [comment]
This also affects the support icon for Earthbreaker and Spellblade
