### ISSUE TITLE
The Discord invitation in README.md appears to be invalid

### ISSUE THREAD

**Issue by gerwaric** [Project-Path-of-Exile-Wiki/PyPoE#175]
The current Discord invitation in [README.md](https://github.com/Project-Path-of-Exile-Wiki/PyPoE/blob/dev/README.md) appears to be invalid. Is this supposed to be the same invitation as the one on the poewiki [Community Portal](https://www.poewiki.net/wiki/Path_of_Exile_Wiki:Community_portal)

**Comment by acbeaumo** [comment]
Fixed. Thanks for reporting.

**Comment by gerwaric** [comment]
Thanks for fixing it. I've just joined, because I'm working on [Acquisition](https://github.com/gerwaric/acquisition), which depends on PyPoE.
