### ISSUE TITLE
pypoe exported Module:Crafting bench/crafting bench options with old parameter

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/PyPoE#24]
In our wiki, the parameter

`crafting_item_class_categories` is removed and replaced by `item_class_categories`

But the pypoe side seem not updated for this part so that the most recent lua export of 

https://www.poewiki.net/wiki/Module:Crafting_bench/crafting_bench_options

still use the old parameter so that it may break other pages that has been updated their cargo query that use `item_class_categories`

**Comment by jacquescorbytuech** [comment]
I've manually updated the page but this needs to be changed in the PyPoE exporter.
