### ISSUE TITLE
[Items export - 3.16] Energy Blade fails to export due to error

### ISSUE THREAD

**Issue by angelic-knight** [Project-Path-of-Exile-Wiki/PyPoE#35]
The new skill, Energy Blade, runs into some disambiguation-type error and fails to export.
Sorry but I can't provide more info right now. I'll update later if I can.

**Comment by angelic-knight** [comment]
Fixed in my fork at commit [dcd5e3c8b38b99ffee92cafd0097a82c57f9b046](https://github.com/angelic-knight/PyPoE/commit/dcd5e3c8b38b99ffee92cafd0097a82c57f9b046#diff-e670fb1cd829f387081b537c6f68eb9ae328f418ffd8e8786176799e76788595)
Just needed to add some suffixes to get added onto the item names to distinguish which item was which (skill gem vs the swords it gives you).

**Comment by markliu06** [comment]
I think Energy Blade the item can be skipped to export. Just like we don't have Steel Shard article (Can't remember the other skills that also create item / weapon in-game for the skill to use, but Vini and i agree that the article can just be deleted and leaving only the skill gem)

**Comment by Journeytojah** [comment]
I agree with @markliu06

**Comment by angelic-knight** [comment]
I'm ok with this, so long as we list the attack speed and crit rate of the swords on the gem page.
Those values will have to then be manually updated with any balance changes

**Comment by markliu06** [comment]
wait.....GGG did not added those info in the gem text?!

**Comment by angelic-knight** [comment]
No, they did not.
1h and 2h swords have different attack speeds as well.

**Comment by markliu06** [comment]
Well if it is not on gem text then there is a reason to export the item. Just should it be on the same page or create two more articles (one-hand and two-hand)

**Comment by angelic-knight** [comment]
This is fixed in the recent merged. It'll export the gem and weapons separately.
