### ISSUE TITLE
[Item export - 3.16] Some base types fail due to conflicts

### ISSUE THREAD

**Issue by angelic-knight** [Project-Path-of-Exile-Wiki/PyPoE#36]
Some base types fail due to conflicts. I'm suspicious this has to do with royale items.
![image](https://user-images.githubusercontent.com/89628672/140247807-24f3c827-cc63-4662-8a4e-f5a1d184d4ed.png)
This needs investigation as to what items are conflicting with these that are failing, and a conflict resolver written to rename or exclude (is this possible?) the duplicates that we don't care about.

**Comment by angelic-knight** [comment]
My branch may have just been out of date with respect to some changes in /patches, or things may have already been identified as royale items and are intentionally being fixed. Worth asking in the tooldev channel about this one before spending time on it.

**Comment by angelic-knight** [comment]
Here's a list of Royale items I found that made it into the wiki:
![image](https://user-images.githubusercontent.com/89628672/141936683-391f63de-fcc4-4f9d-ac97-34852a3427de.png)
They were often causing issues for unique items that had these base types as multiple items of the same name were being found.
They were sometimes usurping links that were meant to go to the real base item instead of the Royale one.

While we could update the unique items to reference page names and fix the other issues, the approach we're going with right now is to exclude Royale items from the wiki.
Cc: @markliu06

**Comment by markliu06** [comment]
As far as i know, if adding the drop disable parameter, then the royal version of the item, will not be picked up by il template

But if we has planned that all these items are not needed, just add to the skip list as well as adding the associated disambiguation for the main item

**Comment by angelic-knight** [comment]
Yeah, we'll need to update this area of item.py:
![image](https://user-images.githubusercontent.com/89628672/141937552-5aebb176-5842-476b-9422-518572cd22ea.png)
I think line 894 there was wrong anyway, it was naming the non-royale bow `... (Royale)`.

**Comment by markliu06** [comment]
>  think line 894 there was wrong anyway

Yes, it seems my typo 

https://github.com/markliu06/PyPoE/commit/395291a4222be1ccbaec3ee20048b824bdce63fc

which probably need to change whole royale disambiguation list to without "Royale" in the metadata id and without the disambiguation term inside ""

`'Metadata/Items/Weapons/TwoHandWeapons/Bows/Bow1 ': "",`

and add the royale item to the skip list somewhere

`'Metadata/Items/Weapons/TwoHandWeapons/Bows/Bow1Royale ',`
