### ISSUE TITLE
Add map boss data

### ISSUE THREAD

**Issue by mark-phaedrus** [Project-Path-of-Exile-Wiki/PyPoE#62]
Currently, the schema does not include any map boss data. This means that Cargo queries cannot duplicate the results of manually-created map lists that include a link to the boss(es) of the map.

**Comment by angelic-knight** [comment]
This seems doable.
Naively, the mapping is Map -> WorldArea -> Bosses_MonsterVarietiesKeys.

**Comment by angelic-knight** [comment]
See the table at https://www.poewiki.net/wiki/Map_bosses
Also https://www.poewiki.net/wiki/Map#Maps_by_level (you may have to look into the history to find the old hand written table)

**Comment by mark-phaedrus** [comment]
The handwritten maps data is also available at https://www.poewiki.net/wiki/List_of_maps_before_3.16 , and will stay there even if [[Map]] is converted to Cargo.

**Comment by angelic-knight** [comment]
The boss info was already being extracted, so I'm closing this issue. It is in the areas cargo table.
