### ISSUE TITLE
DelveLevelScaling.dat: MoreMonsterLife and MoreMonsterDamage are swapped

### ISSUE THREAD

**Issue by Lothrik** [Project-Path-of-Exile-Wiki/PyPoE#67]
From: https://www.poewiki.net/wiki/Module:Delve/delve_level_scaling

```
		depth = 1000, 
		monster_level = 83, 
		sulphite_cost = 1100, 
		darkness_resistance = -801, 
		light_radius = -801, 
		monster_life = 169, 
		monster_damage = 3811, 
```

In: https://github.com/Project-Path-of-Exile-Wiki/PyPoE/blob/dev/PyPoE/poe/file/specification/data/stable.py

For reference, prior to the delve rework the depth 1000 values looked like this:

```
        depth = 1000, 
        monster_level = 83, 
        sulphite_cost = 1100, 
        darkness_resistance = -801, 
        light_radius = -801, 
        monster_life = 300, 
        monster_damage = 600, 
```

GGG definitely did not quintuple monster damage at depth 1000, if anything it's significantly easier to survive in delve now (unless you're zHP -- in which case new sources of unavoidable damage wreck you).

**Comment by pm5k** [comment]
This could be related to #66

**Comment by angelic-knight** [comment]
If the assertion made by this issue is correct, then the values are flipped in the [community's dat spec ](https://github.com/poe-tool-dev/dat-schema) as well.
