### ISSUE TITLE
[Mod export - 3.16]Lure's implicit mods are missing stat text

### ISSUE THREAD

**Issue by markliu06** [Project-Path-of-Exile-Wiki/PyPoE#68]
This is an old issue that reported to OmegaK2 before

https://www.poewiki.net/wiki/Modifier:ScarabBeasts4a
https://www.poewiki.net/wiki/Modifier:ScarabBeasts4b
[https://www.poewiki.net/wiki/Modifier:ScarabBeasts4c~](https://www.poewiki.net/wiki/Modifier:ScarabBeasts4c~)
[https://www.poewiki.net/wiki/Modifier:ScarabBeasts4d~](https://www.poewiki.net/wiki/Modifier:ScarabBeasts4d~)

All 4 lure's implicit mod has missing stat text. Probably pypoe did not read the proper data in .dat and export them

**Comment by angelic-knight** [comment]
This was fixed by #75.
