### ISSUE TITLE
Battlemage's Cry has no _cost_type parameter on export

### ISSUE THREAD

**Issue by Journeytojah** [Project-Path-of-Exile-Wiki/PyPoE#9]
https://www.poewiki.net/wiki/Battlemage%27s_Cry

Cost type doesnt seem to have exported for Battlemage's Cry.

**Comment by markliu06** [comment]
Probably due to it is a hybrid gem . pypoe exported the support part of the data but not the active skill part.

e.g.

`|skill_id                                = BattlemagesCrySupport`


this is an issue for all hybrid gem that may also appears in Spellslinger

**Comment by lvlvllvlvllvlvl** [comment]
looks like this is fixed
